spring:
  datasource:
    url: jdbc:h2:mem:cathaydb
    username: sa
    password: 123456
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  h2:
    console:
      enabled: true